from pptx import Presentation
from pptx.util import Inches, Pt
def build_pptx(project, filename):
    prs = Presentation()
    # title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = project.title
    subtitle.text = 'Generated by AI Doc Platform (mock)'
    for s in sorted(project.sections, key=lambda x: x.order):
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = s.title
        body = slide.shapes.placeholders[1].text_frame
        # naive split into bullets
        lines = (s.content or '').split('.')[:5]
        for ln in lines:
            t = ln.strip()
            if t:
                p = body.add_paragraph()
                p.text = t
    prs.save(filename)
